plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/{rails,rake}'
    - 'test/**/*'
    - "gemfiles/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 150

Metrics/AbcSize:
  Enabled: true
  Max: 21

Metrics/BlockLength:
  Max: 30
  AllowedMethods: ["class_methods"]

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 10

Naming/PredicatePrefix:
  Enabled: false

Rails/Output:
  Enabled: false

Style/Documentation:
  Enabled: false
